### ISSUE TITLE
Can it show the instruction of the origin brightness on the screen？

### ISSUE THREAD

**Issue by lyscop** [JeroenvO/screen-brightness#1]
Hi, 

It is a useful tool that can be used on Win10, and it adjusts the brightness so fast. 

But there is no original instruction on the left-up screen? Can it be achieved with this nice function?

**Comment by JeroenvO** [comment]
I don't know, its a long time ago that i made this and i no longer use it myself.
You could check the original code (link in readme), maybe that can help you.
